<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>vinheta1.utf8.md</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/simplex.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css" data-origin="pandoc">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    background-color: #2a211c;
    color: #bdae9d;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #bdae9d;  padding-left: 4px; }
div.sourceCode
  { color: #bdae9d; background-color: #2a211c; }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ffff00; } /* Alert */
code span.an { color: #0066ff; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { } /* Attribute */
code span.bn { color: #44aa43; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #43a8ed; font-weight: bold; } /* ControlFlow */
code span.ch { color: #049b0a; } /* Char */
code span.cn { } /* Constant */
code span.co { color: #0066ff; font-weight: bold; font-style: italic; } /* Comment */
code span.do { color: #0066ff; font-style: italic; } /* Documentation */
code span.dt { text-decoration: underline; } /* DataType */
code span.dv { color: #44aa43; } /* DecVal */
code span.er { color: #ffff00; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #44aa43; } /* Float */
code span.fu { color: #ff9358; font-weight: bold; } /* Function */
code span.im { } /* Import */
code span.in { color: #0066ff; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #43a8ed; font-weight: bold; } /* Keyword */
code span.op { } /* Operator */
code span.pp { font-weight: bold; } /* Preprocessor */
code span.sc { color: #049b0a; } /* SpecialChar */
code span.ss { color: #049b0a; } /* SpecialString */
code span.st { color: #049b0a; } /* String */
code span.va { } /* Variable */
code span.vs { color: #049b0a; } /* VerbatimString */
code span.wa { color: #ffff00; font-weight: bold; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>


<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 41px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 46px;
  margin-top: -46px;
}
.section h2 {
  padding-top: 46px;
  margin-top: -46px;
}
.section h3 {
  padding-top: 46px;
  margin-top: -46px;
}
.section h4 {
  padding-top: 46px;
  margin-top: -46px;
}
.section h5 {
  padding-top: 46px;
  margin-top: -46px;
}
.section h6 {
  padding-top: 46px;
  margin-top: -46px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Modelos Lineares Generalizados</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fa fa-home"></span>
     
    Home
  </a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fa fa-list-ol"></span>
     
    Material
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="divider"></li>
    <li>
      <a href="vinheta1.html">
        <span class="fa fa-arrow-right"></span>
         
        Regressão Linear com Erros Normais
      </a>
    </li>
    <li class="divider"></li>
    <li>
      <a href="vinheta2.html">
        <span class="fa fa-arrow-right"></span>
         
        Modelos de Regressão para Dados Binários
      </a>
    </li>
    <li class="divider"></li>
    <li>
      <a href="vinheta3.html">
        <span class="fa fa-arrow-right"></span>
         
        Modelos de Regressão para Dados de Contagem
      </a>
    </li>
    <li class="divider"></li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://lineu96.github.io/st/">
    <span class="fa fa-user"></span>
     
    Lineu A.C.F
  </a>
</li>
<li>
  <a href="https://github.com/lineu96">
    <span class="fa fa-github"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">




</div>


<center>
<table>
<tr>
<td>
<img src="img/ufpr.jpg" alt="Drawing" style="width: 200px;"/>
</td>
</tr>
</table>
</center>
<hr />
<p><span class="math display">\[\textbf{Lineu Alberto Cavazani de Freitas}\]</span> <span class="math display">\[\textbf{Prof. Cesar Augusto Taconeli}\]</span> <span class="math display">\[\textbf{Modelos Lineares Generalizados (CE225)}\]</span></p>
<hr />
<center>
<font size="5">
<p align=”center”>
<b> Regressão Linear com Erros Normais </b>
</center>
</font>
</center>
<hr />
<center>
<font size="3">
<p align=”center”>
<b> Consumo de Combustível </b>
</center>
</font>
</center>
<hr />
<div id="dados" class="section level1">
<h1><span class="header-section-number">1</span> Dados</h1>
<hr />
<p>Exemplo disponível em: Paula, G. A. (2004). <a href="https://www.ime.usp.br/~giapaula/texto_2013.pdf">Modelos de regressão: com apoio computacional</a> . São Paulo, SP: IME-USP. (Eg 1.12.5, pág. 94)</p>
<hr />
<p>Dados referentes ao consumo de combustível em 48 estados norte-americanos.</p>
<p>Variáveis:</p>
<ol style="list-style-type: decimal">
<li><strong>taxa</strong>: taxa do combustível no estado em USD,</li>
<li><strong>licença</strong>: proporção de motoristas licenciados,</li>
<li><strong>renda</strong>: renda percapita em USD,</li>
<li><strong>estradas</strong>: ajuda federal para as estradas em mil USD,</li>
<li><strong>consumo</strong>: consumo de combustível por habitante.</li>
</ol>
<p>O objetivo neste estudo é explicar o consumo de combustível pelas variáveis taxa, licença, renda e estradas.</p>
<p>Os dados estão disponíveis no pacote <a href="https://github.com/pet-estatistica/labestData#instalao-e-uso">labestData</a></p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" data-line-number="1"><span class="kw">library</span>(labestData)</a></code></pre></div>
<pre><code>## ----------------------------------------------------------------------
##   labestData: Biblioteca de Dados para Aprendizado de Estatística
## 
##   Para colaboração, suporte ou relato de bugs, visite:
##     http://gitlab.c3sl.ufpr.br/pet-estatistica/labestData,
##     https://github.com/pet-estatistica/labestData
## 
##   labestData version 0.1-1.462 (feito em 2016-08-29) foi carregado.
## ----------------------------------------------------------------------</code></pre>
<p>O pacote fornece, além dos dados, sua documentação e um exemplo de análise. Verifique!</p>
<p>Armazenando a base no objeto <strong>dados</strong>:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" data-line-number="1">dados &lt;-<span class="st"> </span>PaulaEg1.<span class="fl">12.5</span>[ , <span class="dv">-1</span>]</a></code></pre></div>
<p>Primeiras 6 linhas da base:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4-1" data-line-number="1"><span class="kw">head</span>(dados)</a></code></pre></div>
<pre><code>##   taxa licen renda  estr cons
## 1    9 0.525  3571  1976  541
## 2    9 0.580  3865  1586  561
## 3    8 0.544  4399   431  410
## 4    8 0.451  5319 11868  344
## 5    8 0.529  4447  8577  464
## 6    8 0.530  4391  5939  580</code></pre>
<hr />
</div>
<div id="analise-descritiva" class="section level1">
<h1><span class="header-section-number">2</span> Análise Descritiva</h1>
<p>Vamos realizar uma breve análise descritiva dos dados.</p>
<hr />
<div id="medidas-resumo" class="section level2">
<h2><span class="header-section-number">2.1</span> Medidas Resumo</h2>
<p>Usando a função summary verificamos o mínimo, o máximo, a mediana e os quartis para cada variável em estudo.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb6-1" data-line-number="1"><span class="kw">summary</span>(dados)</a></code></pre></div>
<pre><code>##       taxa            licen            renda           estr      
##  Min.   : 5.000   Min.   :0.4510   Min.   :3063   Min.   :  431  
##  1st Qu.: 7.000   1st Qu.:0.5298   1st Qu.:3739   1st Qu.: 3110  
##  Median : 7.500   Median :0.5645   Median :4298   Median : 4736  
##  Mean   : 7.668   Mean   :0.5703   Mean   :4242   Mean   : 5565  
##  3rd Qu.: 8.125   3rd Qu.:0.5952   3rd Qu.:4579   3rd Qu.: 7156  
##  Max.   :10.000   Max.   :0.7240   Max.   :5342   Max.   :17782  
##       cons      
##  Min.   :344.0  
##  1st Qu.:509.5  
##  Median :568.5  
##  Mean   :576.8  
##  3rd Qu.:632.8  
##  Max.   :968.0</code></pre>
<p>As medidas descritivas mostram aparente simetria no que diz respeito às variáveis disponíveis. Nota-se também a grande variação da variável resposta consumo, com valores entre 344 e 968.</p>
<hr />
</div>
<div id="boxplot" class="section level2">
<h2><span class="header-section-number">2.2</span> Boxplot</h2>
<p>O boxplot é uma alternativa de análise descritiva para avaliação da distribuição dos dados.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb8-1" data-line-number="1"><span class="kw">boxplot</span>(dados<span class="op">$</span>cons, <span class="dt">xlab =</span> <span class="st">&#39;Consumo&#39;</span>, <span class="dt">col =</span> <span class="st">&quot;#FFCCCC&quot;</span>)</a></code></pre></div>
<p><img src="vinheta1_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>A verificação do boxplot mostra aparente simetria da variável consumo e a presença de alguns valores atípicos.</p>
<hr />
</div>
<div id="graficos-de-dispersao" class="section level2">
<h2><span class="header-section-number">2.3</span> Gráficos de Dispersão</h2>
<p>Os gráficos de dispersão de cada variável explicativa contra a variável resposta permite verificar, preliminarmente, tendências e valores atípicos.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb9-1" data-line-number="1"><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</a>
<a class="sourceLine" id="cb9-2" data-line-number="2"></a>
<a class="sourceLine" id="cb9-3" data-line-number="3"><span class="kw">plot</span>(cons<span class="op">~</span>taxa, <span class="dt">data =</span> dados, <span class="dt">xlab =</span> <span class="st">&#39;Taxa&#39;</span>, <span class="dt">ylab =</span> <span class="st">&#39;Consumo&#39;</span>)</a>
<a class="sourceLine" id="cb9-4" data-line-number="4"><span class="kw">abline</span>(<span class="kw">lm</span>(cons<span class="op">~</span>taxa, <span class="dt">data =</span> dados), <span class="dt">col=</span><span class="dv">2</span>, <span class="dt">lwd =</span> <span class="dv">2</span>)</a>
<a class="sourceLine" id="cb9-5" data-line-number="5"></a>
<a class="sourceLine" id="cb9-6" data-line-number="6"><span class="kw">plot</span>(cons<span class="op">~</span>licen, <span class="dt">data =</span> dados, <span class="dt">xlab =</span> <span class="st">&#39;Licença&#39;</span>, <span class="dt">ylab =</span> <span class="st">&#39;Consumo&#39;</span>)</a>
<a class="sourceLine" id="cb9-7" data-line-number="7"><span class="kw">abline</span>(<span class="kw">lm</span>(cons<span class="op">~</span>licen, <span class="dt">data =</span> dados), <span class="dt">col =</span> <span class="dv">2</span>, <span class="dt">lwd =</span> <span class="dv">2</span>)</a>
<a class="sourceLine" id="cb9-8" data-line-number="8"></a>
<a class="sourceLine" id="cb9-9" data-line-number="9"><span class="kw">plot</span>(cons<span class="op">~</span>renda, <span class="dt">data =</span> dados, <span class="dt">xlab =</span> <span class="st">&#39;Renda&#39;</span>, <span class="dt">ylab =</span> <span class="st">&#39;Consumo&#39;</span>)</a>
<a class="sourceLine" id="cb9-10" data-line-number="10"><span class="kw">abline</span>(<span class="kw">lm</span>(cons<span class="op">~</span>renda, <span class="dt">data =</span> dados), <span class="dt">col =</span> <span class="dv">2</span>, <span class="dt">lwd =</span> <span class="dv">2</span>)</a>
<a class="sourceLine" id="cb9-11" data-line-number="11"></a>
<a class="sourceLine" id="cb9-12" data-line-number="12"><span class="kw">plot</span>(cons<span class="op">~</span>estr, <span class="dt">data =</span> dados, <span class="dt">xlab =</span> <span class="st">&#39;Estrada&#39;</span>, <span class="dt">ylab =</span> <span class="st">&#39;Consumo&#39;</span>)</a>
<a class="sourceLine" id="cb9-13" data-line-number="13"><span class="kw">abline</span>(<span class="kw">lm</span>(cons<span class="op">~</span>estr, <span class="dt">data =</span> dados), <span class="dt">col =</span> <span class="dv">2</span>, <span class="dt">lwd =</span> <span class="dv">2</span>)</a></code></pre></div>
<p><img src="vinheta1_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>Visualmente, observando a tendência da variável resposta versus cada variável explicativa, vê-se que a que mais aparenta ter relação com o consumo de combustível por habitante é a proporção de motoristas licenciados.</p>
<p>Adicionalmente é recomendável fazer um estudo da matriz de correlaçães dos dados. Para isso, foi utilizado o coeficiente de correlação linear de Pearson.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb10-1" data-line-number="1">cor &lt;-<span class="st"> </span><span class="kw">cor</span>(dados[ ,<span class="op">-</span><span class="dv">1</span>])</a>
<a class="sourceLine" id="cb10-2" data-line-number="2">cor</a></code></pre></div>
<pre><code>##            licen       renda        estr        cons
## licen  1.0000000  0.15707008 -0.06412950  0.69896542
## renda  0.1570701  1.00000000  0.05016279 -0.24486207
## estr  -0.0641295  0.05016279  1.00000000  0.01904194
## cons   0.6989654 -0.24486207  0.01904194  1.00000000</code></pre>
<p>Na matriz de correlação evidencia-se a relação entre consumo e proporção de motoristas licenciados. A correlação entre essas duas variáveis é aproximadamente 0,7. Nota-se também a baixa correlação entre consumo e ajuda federal para as estradas.</p>
<hr />
</div>
<div id="histogramas" class="section level2">
<h2><span class="header-section-number">2.4</span> Histogramas</h2>
<p>O histograma é outra alternativa para observar a forma da distribuição dos dados:</p>
<ul>
<li>Consumo de combustível por Habitante (resposta)</li>
</ul>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb12-1" data-line-number="1"><span class="kw">hist</span>(dados<span class="op">$</span>cons, <span class="dt">probability =</span> <span class="ot">TRUE</span>, <span class="dt">xlab =</span> <span class="st">&#39;Consumo&#39;</span>, <span class="dt">ylab =</span> <span class="st">&#39;Densidade&#39;</span>, </a>
<a class="sourceLine" id="cb12-2" data-line-number="2">     <span class="dt">main =</span> <span class="st">&#39;&#39;</span>, <span class="dt">col =</span> <span class="st">&quot;#FFCCCC&quot;</span>, <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="fl">0.0045</span>))</a>
<a class="sourceLine" id="cb12-3" data-line-number="3"><span class="kw">lines</span>(<span class="kw">density</span>(dados<span class="op">$</span>cons), <span class="dt">col =</span> <span class="st">&quot;#990000&quot;</span>, <span class="dt">lwd =</span> <span class="dv">4</span>)</a></code></pre></div>
<p><img src="vinheta1_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<ul>
<li>Variáveis Explicativas</li>
</ul>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb13-1" data-line-number="1"><span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</a>
<a class="sourceLine" id="cb13-2" data-line-number="2"></a>
<a class="sourceLine" id="cb13-3" data-line-number="3"><span class="kw">hist</span>(dados<span class="op">$</span>taxa, <span class="dt">probability =</span> <span class="ot">TRUE</span>, <span class="dt">xlab =</span> <span class="st">&#39;Taxa&#39;</span>, <span class="dt">ylab =</span> <span class="st">&#39;Densidade&#39;</span>, </a>
<a class="sourceLine" id="cb13-4" data-line-number="4">     <span class="dt">main =</span> <span class="st">&#39;&#39;</span>, <span class="dt">col =</span> <span class="st">&quot;#99FF99&quot;</span>, <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="fl">0.5</span>))</a>
<a class="sourceLine" id="cb13-5" data-line-number="5"><span class="kw">lines</span>(<span class="kw">density</span>(dados<span class="op">$</span>taxa), <span class="dt">col =</span> <span class="st">&quot;#006600&quot;</span>, <span class="dt">lwd =</span> <span class="dv">4</span>)</a>
<a class="sourceLine" id="cb13-6" data-line-number="6"></a>
<a class="sourceLine" id="cb13-7" data-line-number="7"><span class="kw">hist</span>(dados<span class="op">$</span>licen, <span class="dt">probability =</span> <span class="ot">TRUE</span>, <span class="dt">xlab =</span> <span class="st">&#39;licença&#39;</span>, <span class="dt">ylab =</span> <span class="st">&#39;Densidade&#39;</span>, </a>
<a class="sourceLine" id="cb13-8" data-line-number="8">     <span class="dt">main =</span> <span class="st">&#39;&#39;</span>, <span class="dt">col =</span> <span class="st">&quot;#CCFFFF&quot;</span>, <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">8</span>))</a>
<a class="sourceLine" id="cb13-9" data-line-number="9"><span class="kw">lines</span>(<span class="kw">density</span>(dados<span class="op">$</span>licen), <span class="dt">col =</span> <span class="st">&quot;#000099&quot;</span>, <span class="dt">lwd =</span> <span class="dv">4</span>)</a>
<a class="sourceLine" id="cb13-10" data-line-number="10"></a>
<a class="sourceLine" id="cb13-11" data-line-number="11"><span class="kw">hist</span>(dados<span class="op">$</span>renda, <span class="dt">probability =</span> <span class="ot">TRUE</span>, <span class="dt">xlab =</span> <span class="st">&#39;Renda&#39;</span>, <span class="dt">ylab =</span> <span class="st">&#39;Densidade&#39;</span>, </a>
<a class="sourceLine" id="cb13-12" data-line-number="12">     <span class="dt">main =</span> <span class="st">&#39;&#39;</span>, <span class="dt">col =</span> <span class="st">&quot;#FFCCFF&quot;</span>)</a>
<a class="sourceLine" id="cb13-13" data-line-number="13"><span class="kw">lines</span>(<span class="kw">density</span>(dados<span class="op">$</span>renda), <span class="dt">col =</span> <span class="st">&quot;#663366&quot;</span>, <span class="dt">lwd =</span> <span class="dv">4</span>)</a>
<a class="sourceLine" id="cb13-14" data-line-number="14"></a>
<a class="sourceLine" id="cb13-15" data-line-number="15"><span class="kw">hist</span>(dados<span class="op">$</span>estr, <span class="dt">probability =</span> <span class="ot">TRUE</span>, <span class="dt">xlab =</span> <span class="st">&#39;Estrada&#39;</span>, <span class="dt">ylab =</span> <span class="st">&#39;Densidade&#39;</span>, </a>
<a class="sourceLine" id="cb13-16" data-line-number="16">     <span class="dt">main =</span> <span class="st">&#39;&#39;</span>, <span class="dt">col =</span> <span class="st">&quot;#E6E8FA&quot;</span>, <span class="dt">xlim =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="op">+</span><span class="dv">15000</span>))</a>
<a class="sourceLine" id="cb13-17" data-line-number="17"><span class="kw">lines</span>(<span class="kw">density</span>(dados<span class="op">$</span>estr), <span class="dt">col =</span> <span class="st">&quot;#545454&quot;</span>, <span class="dt">lwd =</span> <span class="dv">4</span>)</a></code></pre></div>
<p><img src="vinheta1_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>Marginalmente a variável resposta apresenta distribuição aproximadamente simétrica. Quanto às variáveis explicativas, verifica-se certos desvios de simetria, em especial nas variáveis <strong>taxa</strong> e <strong>estrada</strong>.</p>
<hr />
</div>
</div>
<div id="ajuste-dos-modelos-de-regressao" class="section level1">
<h1><span class="header-section-number">3</span> Ajuste dos Modelos de regressão</h1>
<hr />
<div id="ajuste-1" class="section level2">
<h2><span class="header-section-number">3.1</span> Ajuste 1</h2>
<p>Inicialmente, vamos ajustar o modelo de regressão linear múltipla com todas as variáveis de forma aditiva e todas as observaçães.</p>
<p>A expressão do modelo proposto é dada por:</p>
<p><span class="math display">\[
\newcommand{\undertilde}[1]{\underset{\widetilde{}}{#1}}\]</span></p>
<p><span class="math display">\[y_{i}|\undertilde{x_{i}} \sim Normal(\mu_{i}, \sigma^{2})\]</span> <span class="math display">\[ \newcommand{\undertilde}[1]{\underset{\widetilde{}}{#1}}\]</span> <span class="math display">\[ \mu_{i} = E(y_{i}|\undertilde{x_{i}}) =  {\beta_{0}} + {\beta_{1}}\, taxa_i + {\beta_{2}}\, licen_i + {\beta_{3}}\, renda_i + {\beta_{4}}\, estr_i\]</span></p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb14-1" data-line-number="1">ajuste1 &lt;-<span class="st"> </span><span class="kw">lm</span>(cons <span class="op">~</span><span class="st"> </span>taxa <span class="op">+</span><span class="st"> </span>licen <span class="op">+</span><span class="st"> </span>renda <span class="op">+</span><span class="st"> </span>estr, <span class="dt">data =</span> dados)</a></code></pre></div>
<hr />
<div id="analise-de-residuos" class="section level3">
<h3><span class="header-section-number">3.1.1</span> Análise de Resíduos</h3>
<p>Parte importante da etapa de ajuste de modelos de regressão linear com erros Normais é a análise de resíduos. Nesta fase deve-se verificar os pressupostos do modelo com base na análise dos resíduos: homocedasticidade, Normalidade, independência e identificação de observações discrepantes.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb15-1" data-line-number="1"><span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</a>
<a class="sourceLine" id="cb15-2" data-line-number="2"><span class="kw">plot</span>(ajuste1, <span class="dt">which =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">4</span>)</a></code></pre></div>
<p><img src="vinheta1_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<ul>
<li><p>O gráfico do canto esquerdo superior trás os resíduos ordinários versus os valores ajustados. Esse gráfico é importante para verificação de possíveis padrões não aleatórios, heterocedasticidade, presença de outliers e pontos influentes; o padrão que indica bom ajuste é o de pontos dispersos aleatóriamente e a linha de tendência aproximadamente constante em torno de zero.</p></li>
<li><p>O gráfico do canto direito superior mostra os quantis teóricos da distribuição Normal padrão contra os resíduos padronizados. Esse gráfico permite avaliar a pressuposição de normalidade e, caso não haja normalidade, permite avaliar a forma da distribuição, além de indicar possíveis outliers. Pontos dispersos aleatoriamente, nas proximidades da linha identidade (pontilhada), indicam normalidade.</p></li>
<li><p>O gráfico do canto inferior esquerdo apresenta a raiz quadrada dos resíduos padronizados versus os valores ajustados. Esse gráfico é uma alternativa ao primeiro, baseado nos resíduos padronizados. Tendências nesse gráfico são indicativos de variância não constante.</p></li>
<li><p>E por fim, o gráfico do canto inferior direito apresenta os valores da distância de Cook para cada observação. A distância de Cook é uma medida de diferença das estimativas dos parâmetros do modelo ao considerar e ao desconsiderar uma particular observação no ajuste. Observaçães com valores elevados para essa medida devem ser verificadas.</p></li>
</ul>
<p>Os gráficos de resíduos indicam aparente heterocedasticidade, além de observaçães atípicas.</p>
<hr />
</div>
<div id="verificacao-de-normalidade" class="section level3">
<h3><span class="header-section-number">3.1.2</span> Verificação de Normalidade</h3>
<p>Além do qq-plot é válido explorar outras formas de visualização para verificar aderência dos resíduos à distribuição Normal.</p>
<p>Outra alternativa é fazer uso do teste de Shapiro-Wilk. Trata-se um teste utilizado para verificar se a distribuição de probabilidade associada a um conjunto de dados pode ser aproximada pela distribuição Normal. As hipóteses do teste são:</p>
<p><span class="math display">\[ \begin{matrix} 
H_{0} : \textrm{ Os resíduos   têm   distribuição   normal}
\\ 
H_{1} : \textrm{Os resíduos não têm distribuição normal}
\end{matrix} \]</span></p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb16-1" data-line-number="1"><span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</a>
<a class="sourceLine" id="cb16-2" data-line-number="2"></a>
<a class="sourceLine" id="cb16-3" data-line-number="3"><span class="kw">hist</span>(ajuste1<span class="op">$</span>residuals, <span class="dt">probability =</span> <span class="ot">TRUE</span>, <span class="dt">main =</span> <span class="st">&#39;Resíduos do Ajuste&#39;</span>,</a>
<a class="sourceLine" id="cb16-4" data-line-number="4">      <span class="dt">xlab =</span> <span class="st">&#39;Resíduos&#39;</span>, <span class="dt">ylab =</span> <span class="st">&#39;Frequência&#39;, col = &quot;#FFFFCC&quot;) # histograma dos residuos</span></a>
<a class="sourceLine" id="cb16-5" data-line-number="5"><span class="st"> lines(density(ajuste1$residuals), col = &quot;#666600&quot;, lwd = 4)</span></a>
<a class="sourceLine" id="cb16-6" data-line-number="6"><span class="st"> </span></a>
<a class="sourceLine" id="cb16-7" data-line-number="7"><span class="st"> library(hnp)</span></a>
<a class="sourceLine" id="cb16-8" data-line-number="8"><span class="st"> hnp(ajuste1, main = &#39;</span>Gráfico Normal com Envelope<span class="st">&#39;, xlab = &#39;</span>Quantis Teóricos&#39;, <span class="dt">ylab =</span> <span class="st">&#39;Resíduos&#39;</span>) </a></code></pre></div>
<pre><code>## Gaussian model (lm object)</code></pre>
<p><img src="vinheta1_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb18-1" data-line-number="1"> <span class="kw">shapiro.test</span>(ajuste1<span class="op">$</span>residuals) </a></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  ajuste1$residuals
## W = 0.93918, p-value = 0.0151</code></pre>
<p>A análise gráfica apresenta alguns desvios de normalidade. Quanto ao teste de Shapiro-Wilk, ao nível de significância de 5% há evidência suficiente para a rejeição da hipótese nula.</p>
<hr />
</div>
<div id="medidas-de-infuencia" class="section level3">
<h3><span class="header-section-number">3.1.3</span> Medidas de Infuência</h3>
<p>A função <code>influence.measures</code> retorna diferentes medidas de influência e indica potenciais observaçães influentes no modelo ajustado. São calculados, para cada observação, os valores para DFBETAS, DFFITS, COVRATIO, destância de cook, e os elementos da diagonal da matriz de projeção ortogonal (matriz H).</p>
<p><strong>DFBETAS</strong>: Medida de influência nas estimativas dos parâmetros do modelo (avaliados um a um);</p>
<p><strong>DFFITS</strong>: Medida de diferença nos valores ajustados;</p>
<p><strong>COVRATIO</strong>: Medida de alteração na precisão das estimativas dos parâmetros do modelo;</p>
<p><strong>COOK</strong>: Medida de diferença no conjunto de estimativas dos parâmetros do modelo;</p>
<p><strong>HAT</strong>: Corresponde é diagonal da matriz de projeção da solução de mínimos quadrados. Tais medidas expressam quão extremas são as observaçães no espaço das covariáveis.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb20-1" data-line-number="1">inf &lt;-<span class="st"> </span><span class="kw">influence.measures</span>(ajuste1) </a>
<a class="sourceLine" id="cb20-2" data-line-number="2"><span class="kw">summary</span>(inf)</a></code></pre></div>
<pre><code>## Potentially influential observations of
##   lm(formula = cons ~ taxa + licen + renda + estr, data = dados) :
## 
##    dfb.1_ dfb.taxa dfb.licn dfb.rend dfb.estr dffit   cov.r   cook.d
## 4  -0.01   0.04    -0.15     0.16     0.12     0.28    1.53_*  0.02 
## 19 -0.02   0.03     0.01     0.01    -0.05    -0.09    1.64_*  0.00 
## 27 -0.13   0.14     0.03     0.12     0.01     0.22    1.43_*  0.01 
## 30 -0.08   0.08    -0.04     0.12     0.20     0.27    1.42_*  0.01 
## 44 -0.35  -0.32     1.02_*  -0.02    -0.38     1.49_*  0.18_*  0.31 
##    hat    
## 4   0.28  
## 19  0.32_*
## 27  0.23  
## 30  0.23  
## 44  0.10</code></pre>
<p>Com base nos resultados da análise de influência, deve-se:</p>
<ul>
<li>Estudar os perfis dos indivíduos 4, 19, 27, 30 e 44.</li>
<li>Buscar compreender o motivo dos valores discrepantes para as correspondentes medidas;</li>
<li>Avaliar o efeito dessas observaçães no ajuste (ajustando um novo modelo sem esses dados e comparando os resultados).</li>
</ul>
<hr />
</div>
</div>
<div id="ajuste-2" class="section level2">
<h2><span class="header-section-number">3.2</span> Ajuste 2</h2>
<p>Vamos ajustar o modelo de regressão linear múltipla com todas as variáveis e sem as observaçães 19 e 44, sinalizadas com valores elevados para duas ou mais medidas de influência.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb22-1" data-line-number="1">ajuste2 &lt;-<span class="st"> </span><span class="kw">lm</span>(cons <span class="op">~</span><span class="st"> </span>taxa<span class="op">+</span>licen<span class="op">+</span>renda<span class="op">+</span>estr, <span class="dt">data =</span> dados[<span class="op">-</span><span class="kw">c</span>(<span class="dv">19</span>, <span class="dv">44</span>), ])</a></code></pre></div>
<p>Vamos usar a função <em>compareCoefs</em>, do pacote <em>car</em>, para confrontar os resultados dos dois ajustes:</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb23-1" data-line-number="1"><span class="kw">library</span>(car)</a>
<a class="sourceLine" id="cb23-2" data-line-number="2"><span class="kw">compareCoefs</span>(ajuste1, ajuste2)</a></code></pre></div>
<pre><code>## Calls:
## 1: lm(formula = cons ~ taxa + licen + renda + estr, data = dados)
## 2: lm(formula = cons ~ taxa + licen + renda + estr, data = dados[-c(19,
##    44), ])
## 
##              Model 1  Model 2
## (Intercept)      377      434
## SE               186      158
##                              
## taxa           -34.8    -31.7
## SE              13.0     11.2
##                              
## licen           1336     1173
## SE               192      166
##                              
## renda        -0.0666  -0.0664
## SE            0.0172   0.0145
##                              
## estr        -0.00243 -0.00119
## SE           0.00339  0.00308
## </code></pre>
<p>Embora algumas estimativas e erros padrões tenham seus valores reduzidos após exclusão das duas observaçães, não há alteraçães substanciais quanto às conclusões dos dois modelos (as relaçães estimativa/erro padrão aproximadamente se mantém, os sinais das estimativas são os mesmos).</p>
<p>Vamos avaliar o impacto dessas duas observaçães na distribuição dos resíduos:</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb25-1" data-line-number="1"><span class="kw">require</span>(hnp)</a>
<a class="sourceLine" id="cb25-2" data-line-number="2"><span class="kw">shapiro.test</span>(ajuste2<span class="op">$</span>residuals)</a></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  ajuste2$residuals
## W = 0.97418, p-value = 0.3923</code></pre>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb27-1" data-line-number="1"><span class="kw">hnp</span>(ajuste2)</a></code></pre></div>
<pre><code>## Gaussian model (lm object)</code></pre>
<p><img src="vinheta1_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p>O teste de Shapiro-Wilks e o qq-plot com envelopes simulados indicam agora aderência à distribuição Normal. Para a sequência da análise, no entanto, serão consideradas todas as observaçães, visto que não há alteraçães inferenciais importantes decorrentes da manutenção desses dois pontos.</p>
<p>Para complementar a análise de resíduos, vamos usar os gráficos de componente + resíduos (função <em>crPlots</em> do pacote <em>car</em>). Nesse tipo de gráfico tem-se os resíduos versus cada covariável. No entanto, os resíduos são resultantes do ajuste de todas as demais covariáveis (exceto aquela que aparece no eixo horizontal). Permitem avaliar a necessidade e forma de inclusão de cada covariável ao modelo que contém as demais covariáveis.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb29-1" data-line-number="1"><span class="kw">library</span>(car)</a>
<a class="sourceLine" id="cb29-2" data-line-number="2"><span class="kw">crPlots</span>(ajuste1)</a></code></pre></div>
<p><img src="vinheta1_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p>Pode-se verificar relação decrescente quanto às variáveis <strong>taxa</strong> e <strong>renda</strong> e crescente quanto a <strong>licen</strong>. Com relação é variável <strong>estr</strong>, aparentemente não há relação entre a resposta e essa variável uma vez ajustado o efeito das demais covariáveis.</p>
<hr />
<div id="resumo-do-modelo-ajustado" class="section level3">
<h3><span class="header-section-number">3.2.1</span> Resumo do Modelo Ajustado</h3>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb30-1" data-line-number="1"><span class="kw">summary</span>(ajuste1)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = cons ~ taxa + licen + renda + estr, data = dados)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -122.03  -45.57  -10.66   31.53  234.95 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  3.773e+02  1.855e+02   2.033 0.048207 *  
## taxa        -3.479e+01  1.297e+01  -2.682 0.010332 *  
## licen        1.336e+03  1.923e+02   6.950 1.52e-08 ***
## renda       -6.659e-02  1.722e-02  -3.867 0.000368 ***
## estr        -2.426e-03  3.389e-03  -0.716 0.477999    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 66.31 on 43 degrees of freedom
## Multiple R-squared:  0.6787, Adjusted R-squared:  0.6488 
## F-statistic: 22.71 on 4 and 43 DF,  p-value: 3.907e-10</code></pre>
<p>O resumo indica que as variáveis <strong>taxa</strong>, <strong>licen</strong> e <strong>renda</strong> estão associadas ao consumo, enquanto a variável <strong>estr</strong> não apresenta relação. Vamos ajustar o modelo linear com erros normais agora sem a variável <strong>estr</strong>.</p>
<hr />
</div>
</div>
<div id="ajuste-3" class="section level2">
<h2><span class="header-section-number">3.3</span> Ajuste 3</h2>
<p>Aqui ajustamos o modelo de regressão linear sem a variável ajuda federal para as estradas.</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb32-1" data-line-number="1">ajuste3 &lt;-<span class="st"> </span><span class="kw">lm</span>(cons <span class="op">~</span><span class="st"> </span>taxa <span class="op">+</span><span class="st"> </span>licen <span class="op">+</span><span class="st"> </span>renda, <span class="dt">data =</span> dados)</a></code></pre></div>
<hr />
<div id="analise-de-residuos-1" class="section level3">
<h3><span class="header-section-number">3.3.1</span> Análise de resíduos</h3>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb33-1" data-line-number="1"><span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</a>
<a class="sourceLine" id="cb33-2" data-line-number="2"><span class="kw">plot</span>(ajuste3, <span class="dt">which =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">4</span>)</a></code></pre></div>
<p><img src="vinheta1_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<hr />
</div>
<div id="verificacao-de-normalidade-1" class="section level3">
<h3><span class="header-section-number">3.3.2</span> Verificação de Normalidade</h3>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb34-1" data-line-number="1"><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</a>
<a class="sourceLine" id="cb34-2" data-line-number="2"></a>
<a class="sourceLine" id="cb34-3" data-line-number="3"><span class="kw">hist</span>(ajuste3<span class="op">$</span>residuals, <span class="dt">probability =</span> <span class="ot">TRUE</span>, <span class="dt">main =</span> <span class="st">&#39;Resíduos do Ajuste&#39;</span>,</a>
<a class="sourceLine" id="cb34-4" data-line-number="4">     <span class="dt">xlab =</span> <span class="st">&#39;Resíduos&#39;</span>, <span class="dt">ylab =</span> <span class="st">&#39;Frequência&#39;, col = &quot;#FFFFCC&quot;,</span></a>
<a class="sourceLine" id="cb34-5" data-line-number="5"><span class="st">     ylim = c(0,0.007)) </span></a>
<a class="sourceLine" id="cb34-6" data-line-number="6"></a>
<a class="sourceLine" id="cb34-7" data-line-number="7"><span class="st">lines(density(ajuste3$residuals), col = &quot;#666600&quot;, lwd = 4)</span></a>
<a class="sourceLine" id="cb34-8" data-line-number="8"></a>
<a class="sourceLine" id="cb34-9" data-line-number="9"><span class="st">library(hnp)</span></a>
<a class="sourceLine" id="cb34-10" data-line-number="10"><span class="st"> hnp(ajuste3, main = &#39;</span>Gráfico Normal com Envelope<span class="st">&#39;, xlab = &#39;</span>Quantis Teóricos&#39;, <span class="dt">ylab =</span> <span class="st">&#39;Resíduos&#39;</span>) </a></code></pre></div>
<pre><code>## Gaussian model (lm object)</code></pre>
<p><img src="vinheta1_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb36-1" data-line-number="1"><span class="kw">shapiro.test</span>(ajuste3<span class="op">$</span>residuals)</a></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  ajuste3$residuals
## W = 0.9282, p-value = 0.005858</code></pre>
<p>O resultado do diagnóstico deste ajuste é bastante similar ao verificado para o primeiro modelo. Dessa forma, vamos omitir a etapa de verificação de outliers e observações influentes e seguir para a análise do modelo ajustado.</p>
<hr />
</div>
</div>
</div>
<div id="analise-do-modelo-ajustado" class="section level1">
<h1><span class="header-section-number">4</span> Análise do Modelo Ajustado</h1>
<p>As interpretações são baseadas no ajuste do modelo 3, em que foram considerados os dados dos 48 estados e eliminada a variável referente à ajuda federal.</p>
<hr />
<div id="resumo-do-modelo" class="section level2">
<h2><span class="header-section-number">4.1</span> Resumo do Modelo</h2>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb38-1" data-line-number="1"><span class="kw">summary</span>(ajuste3)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = cons ~ taxa + licen + renda, data = dados)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -110.10  -51.22  -12.89   24.49  238.77 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  307.32790  156.83067   1.960  0.05639 .  
## taxa         -29.48381   10.58358  -2.786  0.00785 ** 
## licen       1374.76841  183.66954   7.485 2.24e-09 ***
## renda         -0.06802    0.01701  -3.999  0.00024 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 65.94 on 44 degrees of freedom
## Multiple R-squared:  0.6749, Adjusted R-squared:  0.6527 
## F-statistic: 30.44 on 3 and 44 DF,  p-value: 8.235e-11</code></pre>
<p>No summary do modelo podemos verificar o coeficiente de variação igual a 0.675, o que indica que 67,5% da variação referente é variável resposta é explicada pelas variáveis regressoras usadas no modelo. Adicionalmente, o teste F correspondente é hipótese nula de não significância do modelo (<span class="math inline">\(H_0: \beta_1 = \beta_2 = \beta_3 = 0\)</span>) produziu p=8.235e-11, indicando a significância do modelo. Cada uma das Variáveis apresentou efeito significativo, ao nível de 5% de significância, ajustado o efeito ads demais covariáveis.</p>
<hr />
</div>
<div id="estimativas" class="section level2">
<h2><span class="header-section-number">4.2</span> Estimativas</h2>
<p>Os valores estimados para os parâmetros do modelo são:</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb40-1" data-line-number="1"><span class="kw">coefficients</span>(ajuste3)</a></code></pre></div>
<pre><code>##   (Intercept)          taxa         licen         renda 
##  307.32789650  -29.48380857 1374.76841106   -0.06802286</code></pre>
<p>E os interavalos com 95% de confiança para os parâmetros do modelo:</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb42-1" data-line-number="1"><span class="kw">confint</span>(ajuste3)</a></code></pre></div>
<pre><code>##                    2.5 %        97.5 %
## (Intercept)   -8.7435503  623.39934333
## taxa         -50.8136042   -8.15401295
## licen       1004.6067761 1744.93004604
## renda         -0.1023038   -0.03374196</code></pre>
<hr />
</div>
<div id="modelo-ajustado" class="section level2">
<h2><span class="header-section-number">4.3</span> Modelo Ajustado</h2>
<p>A expressão do modelo ajustado fica dada por:</p>
<p><span class="math display">\[E[\widehat{y|x}] = 307,32 - 29,48 \,\, taxa_i + 1374,77 \,\, licen_i - 0.07 \,\, renda_i\]</span></p>
<hr />
</div>
<div id="interpretacao-das-estimativas" class="section level2">
<h2><span class="header-section-number">4.4</span> Interpretação das Estimativas</h2>
<ul>
<li><p>Para cada unidade de aumento na variável taxa, estima-se, em média, um decréscimo de aproximadamente 29,49 unidades na variável consumo, mantendo-se fixas as demais variáveis do modelo - IC:(-50,81 ; -8,15);</p></li>
<li><p>Para cada unidade de aumento na variável licen, estima-se, em média, um acréscimo de 1374 unidades na variável consumo, mantendo-se fixas as demais Variáveis do modelo - IC:(1004 ; 1745);</p></li>
<li><p>Para cada unidade de aumento na variável renda, estima-se, em média, um decréscimo de 0,07 unidade na variável consumo - IC:(-0,10 ; -0,03).</p></li>
</ul>
<hr />
</div>
<div id="grafico-de-efeitos" class="section level2">
<h2><span class="header-section-number">4.5</span> Gráfico de Efeitos</h2>
<p>A função effects, do pacote de mesmo nome, devolve os efeitos marginais de cada variável um modelo ajustado; os gráficos de efeitos nos fornecem uma forma visual de observar como cada variável explicativa afeta a resposta, com as demais variáveis fixadas na média.</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb44-1" data-line-number="1"><span class="kw">library</span>(effects)</a>
<a class="sourceLine" id="cb44-2" data-line-number="2"></a>
<a class="sourceLine" id="cb44-3" data-line-number="3"><span class="kw">plot</span>(<span class="kw">allEffects</span>(ajuste3), <span class="dt">type =</span> <span class="st">&#39;response&#39;</span>)</a></code></pre></div>
<p><img src="vinheta1_files/figure-html/unnamed-chunk-25-1.png" width="672" /></p>
<hr />
</div>
<div id="usando-o-modelo-ajustado-para-predicaes" class="section level2">
<h2><span class="header-section-number">4.6</span> Usando o Modelo Ajustado para Prediçães</h2>
<p>Para fins de ilustração, vamos considerar os seguintes perfis para dois estados distintos:</p>
<p><strong>Perfil 1:</strong></p>
<ol style="list-style-type: decimal">
<li>Taxa do combustível no estado = 7.668333</li>
<li>Proporção de motoristas licenciados = 0.5703333</li>
<li>Renda percapita no estado = 4241.833</li>
</ol>
<p><strong>Perfil 2</strong></p>
<ol style="list-style-type: decimal">
<li>Taxa do combustível no estado = 8.483667</li>
<li>Proporção de motoristas licenciados = 0.6258036</li>
<li>Renda percapita no estado = 4815.457</li>
</ol>
<p>E responder a seguinte pergunta: <em>Qual é o consumo médio (ou esperado) de combustível por habitante em estados que tem o Perfil 1 e o Perfil 2?</em></p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb45-1" data-line-number="1">perfis &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">taxa =</span> <span class="kw">c</span>(<span class="fl">7.668333</span>, <span class="fl">8.483667</span>), </a>
<a class="sourceLine" id="cb45-2" data-line-number="2">                     <span class="dt">licen =</span> <span class="kw">c</span>(<span class="fl">0.5703333</span>, <span class="fl">0.6258036</span>), </a>
<a class="sourceLine" id="cb45-3" data-line-number="3">                     <span class="dt">renda =</span> <span class="kw">c</span>(<span class="fl">4241.833</span>, <span class="fl">4815.457</span>))</a></code></pre></div>
<p>Obtemos assim:</p>
<ul>
<li>As estimativas pontuais:</li>
</ul>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb46-1" data-line-number="1"><span class="kw">predict</span>(ajuste3, <span class="dt">newdata =</span> perfis) </a></code></pre></div>
<pre><code>##        1        2 
## 576.7708 589.9709</code></pre>
<ul>
<li>Intervalos de confiança (95%) para o consumo médio médio.</li>
</ul>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb48-1" data-line-number="1"><span class="kw">predict</span>(ajuste3, <span class="dt">interval =</span> <span class="st">&#39;confidence&#39;</span>, <span class="dt">newdata =</span> perfis)</a></code></pre></div>
<pre><code>##        fit      lwr      upr
## 1 576.7708 557.5900 595.9517
## 2 589.9709 551.0998 628.8421</code></pre>
<ul>
<li>Intervalos de confiança (95%) para a predição.</li>
</ul>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb50-1" data-line-number="1"><span class="kw">predict</span>(ajuste3, <span class="dt">interval =</span> <span class="st">&#39;prediction&#39;</span>, <span class="dt">newdata =</span> perfis)</a></code></pre></div>
<pre><code>##        fit      lwr      upr
## 1 576.7708 442.5050 711.0367
## 2 589.9709 451.5138 728.4281</code></pre>
<p>E, finalmente, respondendo a pergunta:</p>
<p>O consumo médio estimado de combustível por habitante de um estado qualquer com o Perfil 1 é igual a 576.77; enquanto para um estado com o Perfil 2 a estimativa é de 589.97.</p>
<hr />
<center>
<table>
<tr>
<td>
<img src="img/logo.png" alt="Drawing" style="width: 200px;"/>
</td>
<td>
<img src="img/LogoB.png" alt="Drawing" style="width: 50px;"/>
</td>
<td>
<img src="img/ufpr.jpg" alt="Drawing" style="width: 200px;"/>
</td>
<td>
<img src="img/LogoB.png" alt="Drawing" style="width: 50px;"/>
</td>
<td>
<img src="img/leg.png" alt="Drawing" style="width: 150px;"/>
</td>
</tr>
</table>
</center>
<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;">

</div>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
